#cloud-config
manage_etc_hosts: true
fqdn: demo.example.com
users:
  # ansible user with sudo rights
  - name: ansible
    gecos: Ansible Account
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id: None
    lock_passwd: false
    # passwd: iamgroot
    passwd: $6$Em.DeoSG1Ua95q$V0V1LydwxpS9G6ERroFTdqJQ5YZ1Q6A4nPOVmKAyCJ7a6x9X02Dn3Za6Yvo3OYCm/LgHqBTtXcUGg5xywNHmN0
    ssh_authorized_keys:
      - ssh-rsa AAAAB3....= your ssh key
runcmd:
    # resize vgsys to disk size
    - growpart /dev/vda 2
    - pvresize /dev/vda2
